version: '3.8'

services:
  kuado:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXTAUTH_URL=https://randevuo.com
      - NEXT_PUBLIC_APP_URL=https://randevuo.com
      - DATABASE_URL=${DATABASE_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=${NEXT_PUBLIC_GOOGLE_MAPS_API_KEY}
      - RESEND_API_KEY=${RESEND_API_KEY}
    restart: unless-stopped
    volumes:
      - ./uploads:/app/public/uploads
    networks:
      - kuado-network

networks:
  kuado-network:
    driver: bridge
